version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8181:80"
        volumes:
            - ./sites/site1:/var/html/site1
            - ./sites/site2:/var/html/site2
            - ./sites/default:/var/html/default
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php

    php:
        image: php:7-fpm
        volumes:
            - ./sites/site1:/var/html/site1
            - ./sites/site2:/var/html/site2
            - ./sites/default:/var/html/default