version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8181:80"
        volumes:
            - ./site1:/site1
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php

    php:
        image: php:7-fpm
        volumes:
            - ./site1:/site1
            - ./site2:/site2